### ISSUE TITLE
New User Signup Persistence 

### ISSUE THREAD

**Issue by micahdevs** [micahives/DnD-MonsterBuilder#30]
Currently the new users I create are reset/not able to login after new pulls from the remote repository, or maybe it's when the cookie expires? I expect a new user that signs up to have an active account unless they choose to remove their account. The database correctly stores new users on my end (including the seed data) and appears to be correctly hashing their passwords.

![Screenshot 2023-12-16 at 10 53 25 AM](https://github.com/micahives/DnD-MonsterBuilder/assets/122231046/f9ff746f-e99b-4f6b-b948-9ac5e981f794)

**Comment by kingbgreen5** [comment]
Hmm mine seems to be saving as i expect. Did you reseed perhaps? That would wipe the db of your previous accounts.
